version: "3.9"
services:

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortcut
      - PGDATA=/var/lib/postgresql/url_shortcut
    volumes:
      - ./db/url_shortcut:/var/lib/postgresql/url_shortcut
    ports:
      - "5435:5432"
    restart: always

  app:
    container_name: shortcut
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db